name: VOx
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - pip
  - numpy
  - nltk
  - wordcloud
  - scikit-learn
  - plotly
  - pytz
  - streamlit
  - newspaper3k
  - pydub
  - python-docx
  - textract
  - Pillow
  - SpeechRecognition
  - pyMuPDF
  - pydub
  - scipy
  
