name: Vox
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.11
  - pip:
    - -r requirements.txt

jobs:
  build:
    name: Installing dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

