name: Vox
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python
  - streamlit
  - plotly
  - newspaper3k
  - nltk
  - wordcloud
  - pandas
  - python-doc
  - PyPDF2
  - textract
  - Pillow
  - docx2txt
  - matplotlib
  - scipy
  - pydub
  - pyaudio
  - scikit-learn
  - SpeechRecognition
