name: Vox
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.11
  - streamlit
  - plotly==4.12.0
  - newspaper3k==0.2.8
  - nltk==3.6.2
  - wordcloud==1.8.1
  - pandas==1.3.3
  - python-docx==0.8.11
  - PyPDF2==1.26.0
  - textract==1.6.3
  - Pillow==8.3.1
  - docx2txt==0.7
  - matplotlib==3.4.3
  - scipy==1.7.3
  - pydub
  - pyaudio==0.2.11
  - scikit-learn==0.24.2
  - SpeechRecognition
