name: VOx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - nltk
  - wordcloud
  - scikit-learn
  - matplotlib
  - plotly
  - requests
  - pytz
  - streamlit
  - newspaper3k
  - python-docx
  - PyPDF2
  - textract
  - pillow
  - fitz
  - pydub
  - scipy
  - speech_recognition
  
