name: VOx
channels:
  - defaults
dependencies:
  - python=3.9  # Specify the Python version you need

  # Add your required packages and their versions here
  - numpy
  - pandas
  - nltk
  - wordcloud
  - scikit-learn
  - newspaper3k
  - matplotlib
  - plotly

  # Additional packages if needed
  - requests
  - docx  # Replace "docx" with "python-docx"
  - pytz
  - streamlit



