name: VOx
channels:
  - python-ci
dependencies:
  - python=3.9
  - numpy
  - nltk
  - wordcloud
  - scikit-learn
  - plotly
  - pytz
  - streamlit
  - newspaper3k
  - docx
  - PyPDF2
  - textract
  - pillow
  - fitz
  - pydub
  - scipy
  - speech_recognition
  
