name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Conda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        conda init bash
        exec bash
      shell: bash

    - name: Install dependencies
      run: |
        while read -r line; do
          conda install $line
        done < requirements.txt

        conda install -c anaconda portaudio
        conda install -c anaconda pyaudio
        # You can also install any other dependencies you have in your environment.yml file.
      shell: bash
