name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install pandas nltk wordcloud scikit-learn newspaper3k matplotlib plotly docx streamlit
        python -m pip install newspaper3k docx PyPDF2 textract fitz pydub scipy
      working-directory: ./

    - name: Display installed packages
      run: |
        python -c "import pkg_resources; print([d for d in pkg_resources.working_set])"

    


